### ISSUE TITLE
Course parsing errors on non-canonical XML

### ISSUE THREAD

**Issue by pwilkins** [mitodl/lore#502] opened 2015-08-12 20:39 UTC
Jolyon reported this issue on CC.801 which has hand-written XML.  For example, this XML skips from chapter to vertical, ignoring the sequential. The result is that LORE doesn't include the complete XML for the chapter.  This is the complete contents of `chapter/week1.xml` which LORE displays in the learningresource pane.  But, this is not the complete XML for the chapter, which Jolyon wants to create a useful export.

```
<chapter display_name="Week 1 (Sept 1-5)" url_name="week1">
    <vertical display_name="Readings and Information" url_name="week1announce">
      <html url_name="week:week1"/>
      <html url_name="about:Syllabus"/>
    </vertical>
</chapter>
```

Interestingly, the complete contents of `chapter/week2.xml` is this:

```
<chapter display_name="Week 2 (Sept 8-12)">
    <vertical display_name="Readings and Information" url_name="week2announce">
      <html url_name="week:week2"/>
      <html url_name="about:Syllabus"/>
    </vertical>
<!--    <sequential url_name="psv:hs01"/>-->
    <sequential url_name="pset:psetol1"/>
    <sequential url_name="pset:psetwr1"/>
    <sequential url_name="pset:psetadv1"/>
</chapter>
```

Yet, LORE does better with this, including the contents of the sequentials in week2's learningresources pane.

In neither case does LORE parse the static assets in the vertical, but let's defer that issue until we decide how we will deal with this one.

@pdpinch @Ferdi

**Comment by ShawnMilo** [comment] 2015-08-12 21:35
Is this course public? If so, please attach a link to it. If not, please let me know where I can get a copy of the whole course directory or tarball.

**Comment by pdpinch** [comment] 2015-09-02 15:46
This course is one of our test courses, but it is not public: https://github.mit.edu/mitx/content-mit-801cc

**Comment by jamiefolsom** [comment] 2015-09-21 17:52
I think you're right, @ShawnMilo. The [description above](https://github.com/mitodl/lore/issues/502#issue-100629859) indicates exactly the issue which was fixed by https://github.com/mitodl/xbundle/pull/44 I think this is a dupe of http://github.com/mitodl/xbundle/issues/43

**Comment by jamiefolsom** [comment] 2015-09-21 18:46
@pdpinch, what @ShawnMilo said in the meeting appears to be true: I can see nothing in this issue that's not covered by https://github.com/mitodl/xbundle/issues/43, and fixed by https://github.com/mitodl/xbundle/pull/44

**Comment by jamiefolsom** [comment] 2015-09-24 18:56
So, @pwilkins, just to confirm, was the problem in the example you gave, that the vertical was not getting ingested? 

So for example, the chapter learning resource called "Week 1 (Sept 1-5)" **did** contain: `<vertical display_name="Readings and Information" url_name="week1announce">`, but the vertical learning resource called "Readings and Information" did not contain the XML **contents** of the file called: `vertical/week1announce`?

If indeed that is the case, can you confirm that for the course called CC-Lite.801, that precise example has the correct contents, instead of the old, incorrect contents? I have just imported that course, and I see that it does have the content I would expect.

http://lore-ci.herokuapp.com/repositories/animating-stuffed-animals/?selected_facets=course_exact%3ACC-Lite.801&selected_facets=resource_type_exact%3Achapter

Thanks!

**Comment by jamiefolsom** [comment] 2015-09-24 20:58
@pwilkins, assigning this one to you. Whoops didn't mean to close. If what you see at that URL is what you expect, would you close this one? Thanks!

**Closed as completed** 2015-09-25 16:04 UTC
Labels: bug

**Comment by pwilkins** [comment] 2015-09-25 16:06
This now displays the expected results.  I tested it on lore-ci with the full CC.801 course.

**Comment by jamiefolsom** [comment] 2015-09-25 21:06
Thanks @pwilkins!
