### ISSUE TITLE
Are we stripping xml markup when indexing content_xml field ?

### ISSUE THREAD

**Issue by Ferdi** [mitodl/lore#202] opened 2015-06-21 16:26 UTC
cc @ShawnMilo

**Comment by ShawnMilo** [comment] 2015-06-21 16:31
Not presently. Do we want to? it wouldn't be difficult. I know it came up in discussion as a question before.

**Comment by pwilkins** [comment] 2015-06-22 14:21
If we strip the XML, how much lose semantic meaning is lost?

**Comment by ShawnMilo** [comment] 2015-06-22 14:49
You'd lose nothing when you clicked "export" or did the preview (once that's working).

If you wanted to actually search by XML tag, like `<section>foo` instead of just `foo`, then you'd lose that. I'd be surprised to learn someone actually wanted to do that, but I can imagine someone copy/pasting a chunk of XML from somewhere and pasting it into the text box. But they'd have an easier time of accomplishing the same thing by using the facets to drill down (course, item type, run, etc.)

The XML markup is already moved in #203. If we want to revert it it only involves removing a few lines.

**Comment by pwilkins** [comment] 2015-06-22 17:51
@ShawnMilo Thank you for the explanation.  I agree that for purposes of searching, the xml tags don't add value.

**Comment by pdpinch** [comment] 2015-06-25 19:09
@shawnmilo I'm still seeing results for searching on tag-like terms, like `<html` e.g. 

http://lore-ci.herokuapp.com/repositories/animating-stuffed-animals/?q=%3Chtml&selected_facets=resource_type_exact:html

**Comment by ShawnMilo** [comment] 2015-06-25 19:11
Yes. It doesn't strip out the HTML, which is itself the "text" content of the XML.

An argument can be made either way. Do you want to change it?

**Comment by Ferdi** [comment] 2015-06-25 19:12
I vote for stripping out all markup

**Comment by ShawnMilo** [comment] 2015-06-25 19:13
Okay. I'll make a new PR.

**Comment by ShawnMilo** [comment] 2015-06-25 22:28
I don't know what the issue is yet, but the HTML is stripped. It's just behaving oddly when you use the `<` character.

For example, if you search for [monkey](http://lore-ci.herokuapp.com/repositories/milo-repo/?q=monkey) you get zero results, but if you search for [<monkey](http://lore-ci.herokuapp.com/repositories/milo-repo/?q=%3Cmonkey) you get a bunch of results.

**Comment by ShawnMilo** [comment] 2015-08-11 14:31
Closing; was accepted it Pivotal #97469022 on August 7th.

**Closed as completed by ShawnMilo** 2015-08-11 14:31 UTC
Labels: work in progress
